### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by SidHarder** [ipfs/js-level-pull-blob-store#2]
@dignifiedquire Friedel, I copied your work from https://github.com/ipfs/js-idb-pull-blob-store and made a few changes to make it work for LevelDb.  This open source stuff is all new to me so I wanted to make sure you get credit. I learned a lot from reading and trying to understand your code.  

I added a statement in the readme giving you credit, If there is something else I should do please let me know.

**Comment by dignifiedquire** [comment]
Hey @SidHarder thank you for writing this :) No worries about the credit, I'm happy you found my code helpful 🎉 

If you could make a PR to https://github.com/ipfs/interface-pull-blob-store so that is listed there as another implementation that would be great.
